locale: "en-US"
site_theme: "default"
title: "Xiao XUE"
title_separator: "-"
name: &name "Xiao XUE"
description: &description "Academic portfolio of Xiao XUE"
url: "https://xuexiao-sean.github.io"
baseurl: ""
repository: "XUEXiao-sean/xuexiao-sean.github.io"

author:
  avatar: "profile.png"
  name: "Xiao XUE"
  pronouns: "He/Him/His"
  bio: "Design researcher working across HCI, RtD, and participatory technology futures"
  location: "Beijing, China"
  employer: "University of Edinburgh"
  uri:
  email: "sean.xue@connect.polyu.hk"
  googlescholar: "https://scholar.google.com/citations?user=ztOba5cAAAAJ&hl=en"
  orcid: "https://orcid.org/0009-0002-7394-4654"
  github: "XUEXiao-sean"
  linkedin:
  focus:
    - "Research through Design"
    - "Participatory AI"
    - "Smart ecosystems"
    - "Co-design"
    - "Technology ethics"

publication_category:
  conferences:
    title: "Conference Papers"
  manuscripts:
    title: "Manuscripts Under Review"

teaser:
breadcrumbs: false
words_per_minute: 160
future: true
read_more: "disabled"
talkmap_link: false

comments:
  provider:

atom_feed:
  hide: false
  path:

analytics:
  provider: "false"

include:
  - .htaccess
  - _pages
  - files

exclude:
  - "Publications _ XUE Xiao, Sean.html"
  - "Publications _ XUE Xiao, Sean_files"
  - CHANGELOG
  - Capfile
  - Gemfile.lock
  - LICENSE
  - README
  - tmp
  - vendor

keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

collections:
  publications:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
  teaching:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: false
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
      share: true
      comments: false
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: false

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
timezone: Asia/Shanghai

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development
